dw:
    worker_node:
        ros__parameters:
            use_gpu: True
            number:
                states: 12
                actions: 6
                iterations: 300 #4000
                episodes: 10000
            hyperparameter:
                alpha: 0.007
                gamma: 0.99
                epsilon: 1.0
            database:
                local_size: 10000
            decay_rate: 10
            training_delay: 0
            hidden_layers: [64,64]
