worker_node:
    use_gpu: True
    number:
        episode_max_steps: 300
        episodes: 10000
    hyperparameter:
        lr: 0.007
        gamma: 0.99
        epsilon: 0.5
    hidden_layers: [64,64]

tester_node:
    use_gpu: True
    number:
        episode_max_steps: 300
        episodes: 10000
    hyperparameter:
        lr: 0.007
        gamma: 0.99
        epsilon: 0.5
    hidden_layers: [64,64]
